/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Curso;
import modelo.Estudiante;
import modelo.RegistroNotasEstudiante;
import modelo.Salon;

/**
 *
 * @author Pixels
 */
public class vistaGestionarCursoDocente extends javax.swing.JFrame {

    private Curso curso;
    private vistaDocente vistaAnterior;
    /**
     * Creates new form vistaGestionarCursoDocente
     * @param curso
     * @param vistaAnterior
     */
    public vistaGestionarCursoDocente(Curso curso, vistaDocente vistaAnterior) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.curso = curso;
        this.vistaAnterior = vistaAnterior;
        crearTablaEstudiantes();
        crearLabels();
        crearComboBox();
        cboxSalon.setSelectedIndex(0);
    }

    public void crearTablaEstudiantes(){
        DefaultTableModel model = new DefaultTableModel();
        String[] columnas = new String[]{
            "Documento", "Nombre","Apellido", "N1","N2", "N3", "Acumulado"
        };
        model.setColumnIdentifiers(columnas);
        for (int i = 0; i < curso.getNotas().getSize(); i++) {
            Estudiante estudiante = curso.getNotas().get(i).getEstudiante();
            model.addRow(new Object[]{
                estudiante.getDocumento(),
                estudiante.getNombre(),
                estudiante.getApellido(),
                Double.toString(curso.getNotas().get(i).getNota1()),
                Double.toString(curso.getNotas().get(i).getNota2()),
                Double.toString(curso.getNotas().get(i).getNota3()),
                String.format("%.3f", curso.getNotas().get(i).getAcumulado()),
            });
        }
        tableEstudiantes.setModel(model);
    }
    
    private void crearLabels(){
        lblAsignatura.setText("Asignatura: " + curso.getAsignatura().getNombre());
        lblDocente.setText("Docente: " + curso.getDocente().getNombre() + " " + curso.getDocente().getApellido());
        lblDia.setText("Día: " + curso.getDia());
        lblHora.setText("Hora: " + consultarHrsCurso(curso));
    }
    
    private String consultarHrsCurso(Curso curso){
        String hrs = "";
        for (int i = 0; i < curso.getHoras().length; i++) {
            hrs += curso.getHoras()[i];
            if(i < curso.getHoras().length-1){
                hrs += ", ";
            }
        }
        return hrs;
    }
    
    private void crearComboBox(){
        cboxSalon.setModel(new DefaultComboBoxModel(vistaAnterior.getControlador().crearArregloSalonesDisponibles(curso)));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblAsignatura = new javax.swing.JLabel();
        lblDocente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        cboxSalon = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEstudiantes = new javax.swing.JTable();
        txtDocumento = new javax.swing.JTextField();
        btnGestionarNotas = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("¡Gestionar curso!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblHora.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblHora.setText("Hora:");
        jPanel1.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lblAsignatura.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblAsignatura.setText("Asignatura:");
        jPanel1.add(lblAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblDocente.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblDocente.setText("Docente:");
        jPanel1.add(lblDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Salón:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        lblDia.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblDia.setText("Día:");
        jPanel1.add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        cboxSalon.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cboxSalon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100" }));
        cboxSalon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxSalonItemStateChanged(evt);
            }
        });
        jPanel1.add(cboxSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Participantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableEstudiantes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tableEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Documento", "Nombre", "Apellido", "N1", "N2", "N3", "Acumulado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEstudiantes.setRowHeight(20);
        tableEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEstudiantes);
        if (tableEstudiantes.getColumnModel().getColumnCount() > 0) {
            tableEstudiantes.getColumnModel().getColumn(0).setResizable(false);
            tableEstudiantes.getColumnModel().getColumn(1).setResizable(false);
            tableEstudiantes.getColumnModel().getColumn(2).setResizable(false);
            tableEstudiantes.getColumnModel().getColumn(3).setResizable(false);
            tableEstudiantes.getColumnModel().getColumn(4).setResizable(false);
            tableEstudiantes.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 510, 210));

        txtDocumento.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtDocumento.setText("Documento...");
        txtDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDocumentoMouseClicked(evt);
            }
        });
        jPanel2.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 100, -1));

        btnGestionarNotas.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnGestionarNotas.setText("Gestionar notas");
        btnGestionarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarNotasActionPerformed(evt);
            }
        });
        jPanel2.add(btnGestionarNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 530, 290));

        btnVolver.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        vistaAnterior.crearTablaCursos();
        vistaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tableEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEstudiantesMouseClicked
        // TODO add your handling code here:
        int seleccion = tableEstudiantes.rowAtPoint(evt.getPoint());
        String documento = tableEstudiantes.getValueAt(seleccion, 0).toString();
        txtDocumento.setText(documento);
    }//GEN-LAST:event_tableEstudiantesMouseClicked

    private void txtDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDocumentoMouseClicked
        // TODO add your handling code here:
        txtDocumento.setText("");
    }//GEN-LAST:event_txtDocumentoMouseClicked

    private void btnGestionarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarNotasActionPerformed
        // TODO add your handling code here:
        RegistroNotasEstudiante registroNotas = curso.buscarRegistroDocumento(txtDocumento.getText());
        if(registroNotas != null){
            new vistaGestionarNotasDocente(registroNotas, this).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No se econtró el estudiante");
        }
    }//GEN-LAST:event_btnGestionarNotasActionPerformed

    private void cboxSalonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxSalonItemStateChanged
        // TODO add your handling code here:
        if(Integer.parseInt(cboxSalon.getSelectedItem().toString()) != curso.getSalon().getNumero()){
            Salon salon = vistaAnterior.getControlador().buscarSalon(Integer.parseInt(cboxSalon.getSelectedItem().toString()));
            if(salon != null){
                curso.setSalon(salon);
                JOptionPane.showMessageDialog(this, "El salón del curso ha sido modificado");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo modificar el salón");
            }
            crearComboBox();
        }
    }//GEN-LAST:event_cboxSalonItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionarNotas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboxSalon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblHora;
    private javax.swing.JTable tableEstudiantes;
    private javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables
}
