/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Controladores.ControladorVistaDocente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Curso;
import modelo.Docente;
import modelo.Universidad;

/**
 *
 * @author Pixels
 */
public class vistaDocente extends javax.swing.JFrame {

    private ControladorVistaDocente controlador;
    private Docente docente;
    /**
     * Creates new form vistaDocente
     * @param docente
     */
    public vistaDocente(Docente docente) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controlador = new ControladorVistaDocente();
        this.docente = docente;
        crearTablaCursos();
        llenarlblsCuenta();
    }

    public ControladorVistaDocente getControlador() {
        return controlador;
    }
    
    public void crearTablaCursos(){
        DefaultTableModel model = new DefaultTableModel();
        String[] columnas = new String[]{
            "Id Curso", "Docente", "Asignatura", "Bloque hrs", "Salón", "Día", "Hrs"
        };
        model.setColumnIdentifiers(columnas);
        for (int i = 0; i < controlador.obtenerCantidadCursosDocente(docente.getUser()); i++) {
            Curso curso = controlador.obtenerCursoDocenteIndex(docente.getUser(), i);
            model.addRow(new Object[]{
                curso.getId(),
                curso.getDocente().getNombre(),
                curso.getAsignatura().getNombre(),
                curso.getBloqueHoras(),
                curso.getSalon().getNumero(),
                curso.getDia(),
                consultarHrsCurso(curso)
            });
        }
        tableCursos.setModel(model);
    }
    
    private String consultarHrsCurso(Curso curso){
        String hrs = "";
        for (int i = 0; i < curso.getHoras().length; i++) {
            hrs += curso.getHoras()[i];
            if(i < curso.getHoras().length-1){
                hrs += ", ";
            }
        }
        return hrs;
    }
    
    private boolean validLtrs(String datos){
        return datos.matches("[a-zA-Z]*");
    }
    
    private boolean validNums(String datos){
        return datos.matches("[0-9]*");
    }
    
    private void llenarlblsCuenta(){
        txtUsuarioCuenta.setText(docente.getUser());
        txtNombreCuenta.setText(docente.getNombre());
        txtApellidoCuenta.setText(docente.getApellido());
        txtDocumentoCuenta.setText(docente.getDocumento());
        txtPswCuenta.setText(docente.getPsw());
        txtPsw2Cuenta.setText(docente.getPsw());
        txtEdadCuenta.setText(Integer.toString(docente.getEdad()));
        txtTelefonoCuenta.setText(docente.getTelefono());
        txtCorreoCuenta.setText(docente.getCorreo());
        txtNivAcademicoCuenta.setText(docente.getNivelAcademico());
        txtEstudiosCuenta.setText(docente.getEstudios());
        txtExpLaboralCuenta.setText(Integer.toString(docente.getExpLaboral()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCursos = new javax.swing.JTable();
        btnGestionarCurso = new javax.swing.JButton();
        txtIdCurso = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtUsuarioCuenta = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtNombreCuenta = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtApellidoCuenta = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtDocumentoCuenta = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txtPswCuenta = new javax.swing.JPasswordField();
        jLabel48 = new javax.swing.JLabel();
        txtPsw2Cuenta = new javax.swing.JPasswordField();
        jLabel50 = new javax.swing.JLabel();
        txtEdadCuenta = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtTelefonoCuenta = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtCorreoCuenta = new javax.swing.JTextField();
        btnEditarCuenta = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtExpLaboralCuenta = new javax.swing.JTextField();
        txtNivAcademicoCuenta = new javax.swing.JTextField();
        txtEstudiosCuenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(802, 400));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(802, 400));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(802, 400));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCursos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tableCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCursos.setRowHeight(25);
        tableCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCursos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 788, 310));

        btnGestionarCurso.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnGestionarCurso.setText("Gestionar curso");
        btnGestionarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarCursoActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        txtIdCurso.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel1.add(txtIdCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 100, -1));

        jTabbedPane1.addTab("Cursos", jPanel1);

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel14.setText("¡Gestionar cuenta!");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel39.setText("Usuario");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        txtUsuarioCuenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtUsuarioCuenta.setEnabled(false);
        jPanel2.add(txtUsuarioCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 100, -1));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel44.setText("Nombre");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 30));

        txtNombreCuenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel2.add(txtNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 100, -1));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel45.setText("Apellido");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        txtApellidoCuenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel2.add(txtApellidoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 100, -1));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel46.setText("Documento");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 30));

        txtDocumentoCuenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtDocumentoCuenta.setEnabled(false);
        jPanel2.add(txtDocumentoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 100, -1));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel47.setText("Contraseña");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 30));

        txtPswCuenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel2.add(txtPswCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 100, -1));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel48.setText("Re.Contraseña");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 30));

        txtPsw2Cuenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel2.add(txtPsw2Cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 100, -1));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel50.setText("Edad");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, 30));

        txtEdadCuenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel2.add(txtEdadCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 100, -1));

        jLabel49.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel49.setText("Telefono");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, 30));

        txtTelefonoCuenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel2.add(txtTelefonoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 100, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel38.setText("Exp. Laboral");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, 30));

        txtCorreoCuenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel2.add(txtCorreoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 100, -1));

        btnEditarCuenta.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btnEditarCuenta.setText("Editar");
        btnEditarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCuentaActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        btnVolver.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btnVolver.setText("Cerrar sesión");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 170, 50));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel40.setText("Correo");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, 30));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel41.setText("Niv. Academico");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, 30));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel42.setText("Estudios");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, 30));

        txtExpLaboralCuenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtExpLaboralCuenta.setEnabled(false);
        jPanel2.add(txtExpLaboralCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 100, -1));

        txtNivAcademicoCuenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtNivAcademicoCuenta.setEnabled(false);
        jPanel2.add(txtNivAcademicoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 100, -1));

        txtEstudiosCuenta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtEstudiosCuenta.setEnabled(false);
        jPanel2.add(txtEstudiosCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 100, -1));

        jTabbedPane1.addTab("Cuenta", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCursosMouseClicked
        // TODO add your handling code here:
        int seleccion = tableCursos.rowAtPoint(evt.getPoint());
        int idCurso = Integer.parseInt(tableCursos.getValueAt(seleccion, 0).toString());
        txtIdCurso.setText(Integer.toString(idCurso));
    }//GEN-LAST:event_tableCursosMouseClicked

    private void btnGestionarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCursoActionPerformed
        // TODO add your handling code here:
        if (validNums(txtIdCurso.getText()) && !txtIdCurso.getText().isEmpty()) {
            int id = Integer.parseInt(txtIdCurso.getText());
            Curso curso = controlador.buscarCursoDocente(id, docente.getUser());
            if (curso != null) {
                new vistaGestionarCursoDocente(curso, this).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el curso");
            }
        }
    }//GEN-LAST:event_btnGestionarCursoActionPerformed

    private void btnEditarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCuentaActionPerformed
        // TODO add your handling code here:
        if(txtNombreCuenta.getText().isEmpty() || txtApellidoCuenta.getText().isEmpty() || txtPswCuenta.getText().isEmpty()
            || txtPsw2Cuenta.getText().isEmpty() || txtEdadCuenta.getText().isEmpty() || txtTelefonoCuenta.getText().isEmpty()
            || txtCorreoCuenta.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
        }else{
            if(validLtrs(txtNombreCuenta.getText()) && validLtrs(txtApellidoCuenta.getText()) && validNums(txtEdadCuenta.getText())
                && validNums(txtTelefonoCuenta.getText())){
                if(txtPswCuenta.getText().equals(txtPsw2Cuenta.getText())){
                    docente.setNombre(txtNombreCuenta.getText());
                    docente.setApellido(txtApellidoCuenta.getText());
                    docente.setPsw(txtPswCuenta.getText());
                    docente.setEdad(Integer.parseInt(txtEdadCuenta.getText()));
                    docente.setTelefono(txtTelefonoCuenta.getText());
                    docente.setCorreo(txtCorreoCuenta.getText());
                    Universidad.serializarUsuarios();
                    JOptionPane.showMessageDialog(this, "Los datos de la cuenta han sido modificados");
                }else{
                    JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Por favor llene todos los campos con los caracteres correctos");
            }
        }
    }//GEN-LAST:event_btnEditarCuentaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new vistaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCuenta;
    private javax.swing.JButton btnGestionarCurso;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableCursos;
    private javax.swing.JTextField txtApellidoCuenta;
    private javax.swing.JTextField txtCorreoCuenta;
    private javax.swing.JTextField txtDocumentoCuenta;
    private javax.swing.JTextField txtEdadCuenta;
    private javax.swing.JTextField txtEstudiosCuenta;
    private javax.swing.JTextField txtExpLaboralCuenta;
    private javax.swing.JTextField txtIdCurso;
    private javax.swing.JTextField txtNivAcademicoCuenta;
    private javax.swing.JTextField txtNombreCuenta;
    private javax.swing.JPasswordField txtPsw2Cuenta;
    private javax.swing.JPasswordField txtPswCuenta;
    private javax.swing.JTextField txtTelefonoCuenta;
    private javax.swing.JTextField txtUsuarioCuenta;
    // End of variables declaration//GEN-END:variables
}
