/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Controladores.ControladorVistaLogin;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.AdminGeneral;
import modelo.AdminLabs;
import modelo.Docente;
import modelo.Estudiante;

/**
 *
 * @author Pixels
 */
public class vistaLogin extends javax.swing.JFrame {
    
    private ControladorVistaLogin controlador;

    /**
     * Creates new form ventanaLogin
     */
    public vistaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        controlador = new ControladorVistaLogin();
    }
    
    private void limpiarCampos(){
        txtUser.setText("");
        txtPsw.setText("");
    }
    
    private void msjContraseniaIncorrecta() {
        JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
        txtPsw.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        txtPsw = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 67, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 102, -1, -1));

        btnIngresar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 143, -1, -1));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 71, 115, 28));

        txtPsw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPswKeyPressed(evt);
            }
        });
        jPanel1.add(txtPsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 108, 115, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        String user = txtUser.getText();
        String psw = txtPsw.getText();

        AdminGeneral adminGeneral = controlador.buscarAdminGeneral(user);
        AdminLabs adminLabs = controlador.buscarAdminLabs(user);
        Docente docente = controlador.buscarDocente(user);
        Estudiante estudiante = controlador.buscarEstudiante(user);
        if (adminGeneral == null && adminLabs == null && docente == null && estudiante == null) {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            limpiarCampos();
        } else {
            if (adminGeneral != null) {
                if (adminGeneral.getPsw().equals(psw)) {
                    new vistaAdminGeneral(adminGeneral).setVisible(true);
                    this.dispose();
                } else {
                    msjContraseniaIncorrecta();
                }
            } else if (adminLabs != null) {
                if (adminLabs.getPsw().equals(psw)) {
                    new vistaAdminLabs(adminLabs).setVisible(true);
                    this.dispose();
                } else {
                    msjContraseniaIncorrecta();
                }
            } else if (estudiante != null) {
                if (estudiante.getPsw().equals(psw)) {
                    new vistaEstudiante(estudiante).setVisible(true);
                    this.dispose();
                } else {
                    msjContraseniaIncorrecta();
                }
            } else if (docente != null) {
                if (docente.getPsw().equals(psw)) {
                    new vistaDocente(docente).setVisible(true);
                    this.dispose();
                } else {
                    msjContraseniaIncorrecta();
                }
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtPswKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPswKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnIngresar.doClick();
        }
    }//GEN-LAST:event_txtPswKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPsw;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
