/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.RegistroNotasEstudiante;

/**
 *
 * @author Pixels
 */
public class vistaGestionarNotasDocente extends javax.swing.JFrame {

    private RegistroNotasEstudiante notas;
    private vistaGestionarCursoDocente vistaAnterior;
    /**
     * Creates new form vistaGestionarNotasDocente
     * @param notas
     * @param vistaAnterior
     */
    public vistaGestionarNotasDocente(RegistroNotasEstudiante notas, vistaGestionarCursoDocente vistaAnterior) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.notas = notas;
        this.vistaAnterior = vistaAnterior;
        lblNombreEstudiante.setText(notas.getEstudiante().getNombre() + " " + notas.getEstudiante().getApellido());
        llenarNotas();
    }
    
    private void llenarNotas(){
        txtN1.setText(Double.toString(notas.getNota1()));
        txtN2.setText(Double.toString(notas.getNota2()));
        txtN3.setText(Double.toString(notas.getNota3()));
        txtAcumulado.setText(String.format("%.3f", notas.getAcumulado()));
    }

    private boolean validNums(String datos){
        return datos.matches("[0-9.]*");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreEstudiante = new javax.swing.JLabel();
        lblNota1 = new javax.swing.JLabel();
        lblNota2 = new javax.swing.JLabel();
        lblAcumulado = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtAcumulado = new javax.swing.JTextField();
        txtN1 = new javax.swing.JTextField();
        txtN2 = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblNota3 = new javax.swing.JLabel();
        txtN3 = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreEstudiante.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblNombreEstudiante.setText("Nombre");
        jPanel1.add(lblNombreEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblNota1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblNota1.setText("Nota 1");
        jPanel1.add(lblNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblNota2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblNota2.setText("Nota 2");
        jPanel1.add(lblNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        lblAcumulado.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblAcumulado.setText("Acumulado");
        jPanel1.add(lblAcumulado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTitulo.setText("¡Gestionar notas de estudiante!");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtAcumulado.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtAcumulado.setEnabled(false);
        jPanel1.add(txtAcumulado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 90, -1));

        txtN1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel1.add(txtN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, -1));

        txtN2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel1.add(txtN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 50, -1));

        btnAceptar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("Asignar nota:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lblNota3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblNota3.setText("Nota 3");
        jPanel1.add(lblNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        txtN3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jPanel1.add(txtN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 50, -1));

        btnVolver.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if(txtN1.getText().isEmpty() || txtN2.getText().isEmpty() || txtN3.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
        }else{
            if(validNums(txtN1.getText()) && validNums(txtN2.getText()) && validNums(txtN3.getText())){
                notas.setNota1(Double.parseDouble(txtN1.getText()));
                notas.setNota2(Double.parseDouble(txtN2.getText()));
                notas.setNota3(Double.parseDouble(txtN3.getText()));
                txtAcumulado.setText(String.format("%.3f", notas.getAcumulado()));
                vistaAnterior.crearTablaEstudiantes();
                JOptionPane.showMessageDialog(this, "Las notas del estudiante han sido actualizadas");
            }else{
                JOptionPane.showMessageDialog(this, "Por favor ingrese caracteres válidos");
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        vistaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAcumulado;
    private javax.swing.JLabel lblNombreEstudiante;
    private javax.swing.JLabel lblNota1;
    private javax.swing.JLabel lblNota2;
    private javax.swing.JLabel lblNota3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAcumulado;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN2;
    private javax.swing.JTextField txtN3;
    // End of variables declaration//GEN-END:variables
}
