/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Controladores.ControladorVistaAdminLabs;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Herramienta;
import modelo.Laboratorio;
import modelo.OcupanteYPrestamo;

/**
 *
 * @author Pixels
 */
public class vistaGestionarPrestamoOcupante extends javax.swing.JFrame {

    private OcupanteYPrestamo prestamo;
    private Laboratorio lab;
    private vistaGestionLab vistaAnterior;
    private ControladorVistaAdminLabs controlador;
    private int idHerramienta;
    private int idHerramientaPrestada;
    /**
     * Creates new form vistaGestionarPrestamoOcupante
     */
    public vistaGestionarPrestamoOcupante(OcupanteYPrestamo prestamo, Laboratorio lab, ControladorVistaAdminLabs controlador, vistaGestionLab vistaAnterior) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.prestamo = prestamo;
        this.lab = lab;
        this.controlador = controlador;
        this.vistaAnterior = vistaAnterior;
        llenarLabels();
        crearTablaHerramientasPrestadas();
        crearTablaPrestarHerramientas();
    }
    
    private void llenarLabels(){
        lblEstudiante.setText("Estudiante: " + prestamo.getEstudiante().getNombre() + " " + prestamo.getEstudiante().getApellido() + ".");
        lblDocumento.setText("Documento: " + prestamo.getEstudiante().getDocumento());
        lblTelefono.setText("Telefono: " + prestamo.getEstudiante().getTelefono());
        lblEdad.setText("Edad: " + prestamo.getEstudiante().getEdad());
        lblCorreo.setText("Correo: " + prestamo.getEstudiante().getCorreo());
    }
    
    private void crearTablaHerramientasPrestadas(){
        DefaultTableModel model = new DefaultTableModel();
        String[] columnas = new String[]{
            "id", "Nombre","Tipo"
        };
        model.setColumnIdentifiers(columnas);
        for (int i = 0; i < prestamo.getHerramientas().getSize(); i++) {
            Herramienta herramienta = prestamo.getHerramientas().get(i);
            model.addRow(new Object[]{
                herramienta.getId(),
                herramienta.getNombre(),
                herramienta.getTipo(),
            });
        }
        tableHerramientasPrestadas.setModel(model);
    }
    
    private void crearTablaPrestarHerramientas(){
        DefaultTableModel model = new DefaultTableModel();
        String[] columnas = new String[]{
            "id", "Nombre","Tipo"
        };
        model.setColumnIdentifiers(columnas);
        for (int i = 0; i < controlador.obtenerCantidadHerramientasDisponibles(); i++) {
            Herramienta herramienta = controlador.obtenerHerramientaDisponibleIndex(i);
            model.addRow(new Object[]{
                herramienta.getId(),
                herramienta.getNombre(),
                herramienta.getTipo(),
            });
        }
        tablePrestarHerramientas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblEstudiante = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHerramientasPrestadas = new javax.swing.JTable();
        btnDevolverHerramienta = new javax.swing.JButton();
        panelPrestarHerramienta = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePrestarHerramientas = new javax.swing.JTable();
        btnPrestarHerramienta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("¡Gestionar prestamo!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblDocumento.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblDocumento.setText("Documento:");
        jPanel1.add(lblDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblCorreo.setText("Correo:");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        lblEstudiante.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblEstudiante.setText("Estudiante:");
        jPanel1.add(lblEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblTelefono.setText("Telefono:");
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblEdad.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblEdad.setText("Edad:");
        jPanel1.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        btnVolver.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Herramientas  prestadas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        tableHerramientasPrestadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableHerramientasPrestadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHerramientasPrestadasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHerramientasPrestadas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 370, 130));

        btnDevolverHerramienta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnDevolverHerramienta.setText("Devolver herramienta");
        btnDevolverHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverHerramientaActionPerformed(evt);
            }
        });
        jPanel1.add(btnDevolverHerramienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        panelPrestarHerramienta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Prestar herramienta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 24))); // NOI18N
        panelPrestarHerramienta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablePrestarHerramientas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePrestarHerramientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePrestarHerramientasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePrestarHerramientas);

        panelPrestarHerramienta.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 37, 381, 340));

        btnPrestarHerramienta.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnPrestarHerramienta.setText("Prestar herramienta");
        btnPrestarHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarHerramientaActionPerformed(evt);
            }
        });
        panelPrestarHerramienta.add(btnPrestarHerramienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        jPanel1.add(panelPrestarHerramienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 400, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableHerramientasPrestadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHerramientasPrestadasMouseClicked
        // TODO add your handling code here:
        int seleccion = tableHerramientasPrestadas.rowAtPoint(evt.getPoint());
        idHerramientaPrestada = Integer.parseInt(tableHerramientasPrestadas.getValueAt(seleccion, 0).toString());
    }//GEN-LAST:event_tableHerramientasPrestadasMouseClicked

    private void tablePrestarHerramientasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePrestarHerramientasMouseClicked
        // TODO add your handling code here:
        int seleccion = tablePrestarHerramientas.rowAtPoint(evt.getPoint());
        idHerramienta = Integer.parseInt(tablePrestarHerramientas.getValueAt(seleccion, 0).toString());
    }//GEN-LAST:event_tablePrestarHerramientasMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        vistaAnterior.crearTablaEstudiantes();
        vistaAnterior.crearTablaHerramientas();
        vistaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnDevolverHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverHerramientaActionPerformed
        // TODO add your handling code here:
        Herramienta aux = lab.buscarHerramienta(idHerramientaPrestada);
        if (aux != null) {
            int i = JOptionPane.showConfirmDialog(this, "¿Está seguro de devolver la herramienta " + aux.getNombre() + "?");
            if (i == 0) {
                boolean aux2 = lab.devolverHerramienta(idHerramientaPrestada);
                if (aux2) {
                    JOptionPane.showMessageDialog(this, "La herramienta ha sido devuelta satisfactoriamente");
                    crearTablaHerramientasPrestadas();
                    crearTablaPrestarHerramientas();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una herramienta en la tabla para devolverla");
        }
    }//GEN-LAST:event_btnDevolverHerramientaActionPerformed

    private void btnPrestarHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarHerramientaActionPerformed
        // TODO add your handling code here:
        Herramienta herramienta = controlador.buscarHerramientaDisponible(idHerramienta);
        if(herramienta != null){
            boolean aux = lab.validarHerramienta(herramienta.getTipo());
            if(aux){
                prestamo.prestarHerramienta(herramienta);
                crearTablaHerramientasPrestadas();
                crearTablaPrestarHerramientas();
                JOptionPane.showMessageDialog(this, "La herramienta ha sido prestada a " + prestamo.getEstudiante().getNombre());
            }else{
                JOptionPane.showMessageDialog(this, "No se pueden prestar más de dos herramientas del mismo tipo en el laboratorio");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Por favor seleccione una herramienta en la tabla para prestarla");
        }
    }//GEN-LAST:event_btnPrestarHerramientaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolverHerramienta;
    private javax.swing.JButton btnPrestarHerramienta;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel panelPrestarHerramienta;
    private javax.swing.JTable tableHerramientasPrestadas;
    private javax.swing.JTable tablePrestarHerramientas;
    // End of variables declaration//GEN-END:variables
}
